//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lystikaServer.n11ProductSellingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.n11.com/ws/schemas", ConfigurationName="n11ProductSellingService.ProductSellingServicePort")]
    public interface ProductSellingServicePort {
        
        // CODEGEN: StopSellingProductByProductId işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductSkuBasicRequest))]
        lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse1 StopSellingProductByProductId(lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse1> StopSellingProductByProductIdAsync(lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest1 request);
        
        // CODEGEN: StopSellingProductBySellerCode işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductSkuBasicRequest))]
        lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse1 StopSellingProductBySellerCode(lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse1> StopSellingProductBySellerCodeAsync(lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest1 request);
        
        // CODEGEN: StartSellingProductByProductId işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductSkuBasicRequest))]
        lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse1 StartSellingProductByProductId(lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse1> StartSellingProductByProductIdAsync(lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest1 request);
        
        // CODEGEN: StartSellingProductBySellerCode işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductSkuBasicRequest))]
        lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse1 StartSellingProductBySellerCode(lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse1> StartSellingProductBySellerCodeAsync(lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StopSellingProductByProductIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long productIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appKeyField;
        
        private string appSecretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("appKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appSecret {
            get {
                return this.appSecretField;
            }
            set {
                this.appSecretField = value;
                this.RaisePropertyChanged("appSecret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSkuBasic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSku))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSkuBasicRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sellerStockCodeField;
        
        private decimal optionPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sellerStockCode {
            get {
                return this.sellerStockCodeField;
            }
            set {
                this.sellerStockCodeField = value;
                this.RaisePropertyChanged("sellerStockCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal optionPrice {
            get {
                return this.optionPriceField;
            }
            set {
                this.optionPriceField = value;
                this.RaisePropertyChanged("optionPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSku))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSkuBasic : ProductSkuBasicRequest {
        
        private decimal currencyAmountField;
        
        private decimal displayPriceField;
        
        private decimal oldOptionPriceField;
        
        private string gtinField;
        
        private string mpnField;
        
        private string oemField;
        
        private bool bundleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal currencyAmount {
            get {
                return this.currencyAmountField;
            }
            set {
                this.currencyAmountField = value;
                this.RaisePropertyChanged("currencyAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal displayPrice {
            get {
                return this.displayPriceField;
            }
            set {
                this.displayPriceField = value;
                this.RaisePropertyChanged("displayPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal oldOptionPrice {
            get {
                return this.oldOptionPriceField;
            }
            set {
                this.oldOptionPriceField = value;
                this.RaisePropertyChanged("oldOptionPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string gtin {
            get {
                return this.gtinField;
            }
            set {
                this.gtinField = value;
                this.RaisePropertyChanged("gtin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mpn {
            get {
                return this.mpnField;
            }
            set {
                this.mpnField = value;
                this.RaisePropertyChanged("mpn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string oem {
            get {
                return this.oemField;
            }
            set {
                this.oemField = value;
                this.RaisePropertyChanged("oem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool bundle {
            get {
                return this.bundleField;
            }
            set {
                this.bundleField = value;
                this.RaisePropertyChanged("bundle");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSku : ProductSkuBasic {
        
        private long idField;
        
        private long versionField;
        
        private string quantityField;
        
        private ProductAttribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSkuList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private ProductSku[] stockItemField;
        
        private string productSellerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductSku[] stockItem {
            get {
                return this.stockItemField;
            }
            set {
                this.stockItemField = value;
                this.RaisePropertyChanged("stockItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
                this.RaisePropertyChanged("productSellerCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductBasic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string productSellerCodeField;
        
        private string titleField;
        
        private string subtitleField;
        
        private decimal priceField;
        
        private decimal displayPriceField;
        
        private bool isDomesticField;
        
        private string saleStatusField;
        
        private string approvalStatusField;
        
        private ProductSkuList stockItemsField;
        
        private decimal oldPriceField;
        
        private decimal currencyAmountField;
        
        private string currencyTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
                this.RaisePropertyChanged("productSellerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
                this.RaisePropertyChanged("subtitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal displayPrice {
            get {
                return this.displayPriceField;
            }
            set {
                this.displayPriceField = value;
                this.RaisePropertyChanged("displayPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool isDomestic {
            get {
                return this.isDomesticField;
            }
            set {
                this.isDomesticField = value;
                this.RaisePropertyChanged("isDomestic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=7)]
        public string saleStatus {
            get {
                return this.saleStatusField;
            }
            set {
                this.saleStatusField = value;
                this.RaisePropertyChanged("saleStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", IsNullable=true, Order=8)]
        public string approvalStatus {
            get {
                return this.approvalStatusField;
            }
            set {
                this.approvalStatusField = value;
                this.RaisePropertyChanged("approvalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ProductSkuList stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal oldPrice {
            get {
                return this.oldPriceField;
            }
            set {
                this.oldPriceField = value;
                this.RaisePropertyChanged("oldPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal currencyAmount {
            get {
                return this.currencyAmountField;
            }
            set {
                this.currencyAmountField = value;
                this.RaisePropertyChanged("currencyAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=12)]
        public string currencyType {
            get {
                return this.currencyTypeField;
            }
            set {
                this.currencyTypeField = value;
                this.RaisePropertyChanged("currencyType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
                this.RaisePropertyChanged("errorCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StopSellingProductByProductIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ProductBasic productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductBasic product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StopSellingProductByProductIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest StopSellingProductByProductIdRequest;
        
        public StopSellingProductByProductIdRequest1() {
        }
        
        public StopSellingProductByProductIdRequest1(lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest StopSellingProductByProductIdRequest) {
            this.StopSellingProductByProductIdRequest = StopSellingProductByProductIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StopSellingProductByProductIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse StopSellingProductByProductIdResponse;
        
        public StopSellingProductByProductIdResponse1() {
        }
        
        public StopSellingProductByProductIdResponse1(lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse StopSellingProductByProductIdResponse) {
            this.StopSellingProductByProductIdResponse = StopSellingProductByProductIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StopSellingProductBySellerCodeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private string productSellerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
                this.RaisePropertyChanged("productSellerCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StopSellingProductBySellerCodeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ProductBasic productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductBasic product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StopSellingProductBySellerCodeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest StopSellingProductBySellerCodeRequest;
        
        public StopSellingProductBySellerCodeRequest1() {
        }
        
        public StopSellingProductBySellerCodeRequest1(lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest StopSellingProductBySellerCodeRequest) {
            this.StopSellingProductBySellerCodeRequest = StopSellingProductBySellerCodeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StopSellingProductBySellerCodeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse StopSellingProductBySellerCodeResponse;
        
        public StopSellingProductBySellerCodeResponse1() {
        }
        
        public StopSellingProductBySellerCodeResponse1(lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse StopSellingProductBySellerCodeResponse) {
            this.StopSellingProductBySellerCodeResponse = StopSellingProductBySellerCodeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StartSellingProductByProductIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long productIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StartSellingProductByProductIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ProductBasic productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductBasic product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartSellingProductByProductIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest StartSellingProductByProductIdRequest;
        
        public StartSellingProductByProductIdRequest1() {
        }
        
        public StartSellingProductByProductIdRequest1(lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest StartSellingProductByProductIdRequest) {
            this.StartSellingProductByProductIdRequest = StartSellingProductByProductIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartSellingProductByProductIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse StartSellingProductByProductIdResponse;
        
        public StartSellingProductByProductIdResponse1() {
        }
        
        public StartSellingProductByProductIdResponse1(lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse StartSellingProductByProductIdResponse) {
            this.StartSellingProductByProductIdResponse = StartSellingProductByProductIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StartSellingProductBySellerCodeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private string productSellerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
                this.RaisePropertyChanged("productSellerCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class StartSellingProductBySellerCodeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ProductBasic productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductBasic product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartSellingProductBySellerCodeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest StartSellingProductBySellerCodeRequest;
        
        public StartSellingProductBySellerCodeRequest1() {
        }
        
        public StartSellingProductBySellerCodeRequest1(lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest StartSellingProductBySellerCodeRequest) {
            this.StartSellingProductBySellerCodeRequest = StartSellingProductBySellerCodeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartSellingProductBySellerCodeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse StartSellingProductBySellerCodeResponse;
        
        public StartSellingProductBySellerCodeResponse1() {
        }
        
        public StartSellingProductBySellerCodeResponse1(lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse StartSellingProductBySellerCodeResponse) {
            this.StartSellingProductBySellerCodeResponse = StartSellingProductBySellerCodeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductSellingServicePortChannel : lystikaServer.n11ProductSellingService.ProductSellingServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductSellingServicePortClient : System.ServiceModel.ClientBase<lystikaServer.n11ProductSellingService.ProductSellingServicePort>, lystikaServer.n11ProductSellingService.ProductSellingServicePort {
        
        public ProductSellingServicePortClient() {
        }
        
        public ProductSellingServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductSellingServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductSellingServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductSellingServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse1 lystikaServer.n11ProductSellingService.ProductSellingServicePort.StopSellingProductByProductId(lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest1 request) {
            return base.Channel.StopSellingProductByProductId(request);
        }
        
        public lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse StopSellingProductByProductId(lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest StopSellingProductByProductIdRequest) {
            lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest1 inValue = new lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest1();
            inValue.StopSellingProductByProductIdRequest = StopSellingProductByProductIdRequest;
            lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse1 retVal = ((lystikaServer.n11ProductSellingService.ProductSellingServicePort)(this)).StopSellingProductByProductId(inValue);
            return retVal.StopSellingProductByProductIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse1> lystikaServer.n11ProductSellingService.ProductSellingServicePort.StopSellingProductByProductIdAsync(lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest1 request) {
            return base.Channel.StopSellingProductByProductIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StopSellingProductByProductIdResponse1> StopSellingProductByProductIdAsync(lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest StopSellingProductByProductIdRequest) {
            lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest1 inValue = new lystikaServer.n11ProductSellingService.StopSellingProductByProductIdRequest1();
            inValue.StopSellingProductByProductIdRequest = StopSellingProductByProductIdRequest;
            return ((lystikaServer.n11ProductSellingService.ProductSellingServicePort)(this)).StopSellingProductByProductIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse1 lystikaServer.n11ProductSellingService.ProductSellingServicePort.StopSellingProductBySellerCode(lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest1 request) {
            return base.Channel.StopSellingProductBySellerCode(request);
        }
        
        public lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse StopSellingProductBySellerCode(lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest StopSellingProductBySellerCodeRequest) {
            lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest1 inValue = new lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest1();
            inValue.StopSellingProductBySellerCodeRequest = StopSellingProductBySellerCodeRequest;
            lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse1 retVal = ((lystikaServer.n11ProductSellingService.ProductSellingServicePort)(this)).StopSellingProductBySellerCode(inValue);
            return retVal.StopSellingProductBySellerCodeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse1> lystikaServer.n11ProductSellingService.ProductSellingServicePort.StopSellingProductBySellerCodeAsync(lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest1 request) {
            return base.Channel.StopSellingProductBySellerCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeResponse1> StopSellingProductBySellerCodeAsync(lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest StopSellingProductBySellerCodeRequest) {
            lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest1 inValue = new lystikaServer.n11ProductSellingService.StopSellingProductBySellerCodeRequest1();
            inValue.StopSellingProductBySellerCodeRequest = StopSellingProductBySellerCodeRequest;
            return ((lystikaServer.n11ProductSellingService.ProductSellingServicePort)(this)).StopSellingProductBySellerCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse1 lystikaServer.n11ProductSellingService.ProductSellingServicePort.StartSellingProductByProductId(lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest1 request) {
            return base.Channel.StartSellingProductByProductId(request);
        }
        
        public lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse StartSellingProductByProductId(lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest StartSellingProductByProductIdRequest) {
            lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest1 inValue = new lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest1();
            inValue.StartSellingProductByProductIdRequest = StartSellingProductByProductIdRequest;
            lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse1 retVal = ((lystikaServer.n11ProductSellingService.ProductSellingServicePort)(this)).StartSellingProductByProductId(inValue);
            return retVal.StartSellingProductByProductIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse1> lystikaServer.n11ProductSellingService.ProductSellingServicePort.StartSellingProductByProductIdAsync(lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest1 request) {
            return base.Channel.StartSellingProductByProductIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StartSellingProductByProductIdResponse1> StartSellingProductByProductIdAsync(lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest StartSellingProductByProductIdRequest) {
            lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest1 inValue = new lystikaServer.n11ProductSellingService.StartSellingProductByProductIdRequest1();
            inValue.StartSellingProductByProductIdRequest = StartSellingProductByProductIdRequest;
            return ((lystikaServer.n11ProductSellingService.ProductSellingServicePort)(this)).StartSellingProductByProductIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse1 lystikaServer.n11ProductSellingService.ProductSellingServicePort.StartSellingProductBySellerCode(lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest1 request) {
            return base.Channel.StartSellingProductBySellerCode(request);
        }
        
        public lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse StartSellingProductBySellerCode(lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest StartSellingProductBySellerCodeRequest) {
            lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest1 inValue = new lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest1();
            inValue.StartSellingProductBySellerCodeRequest = StartSellingProductBySellerCodeRequest;
            lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse1 retVal = ((lystikaServer.n11ProductSellingService.ProductSellingServicePort)(this)).StartSellingProductBySellerCode(inValue);
            return retVal.StartSellingProductBySellerCodeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse1> lystikaServer.n11ProductSellingService.ProductSellingServicePort.StartSellingProductBySellerCodeAsync(lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest1 request) {
            return base.Channel.StartSellingProductBySellerCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeResponse1> StartSellingProductBySellerCodeAsync(lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest StartSellingProductBySellerCodeRequest) {
            lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest1 inValue = new lystikaServer.n11ProductSellingService.StartSellingProductBySellerCodeRequest1();
            inValue.StartSellingProductBySellerCodeRequest = StartSellingProductBySellerCodeRequest;
            return ((lystikaServer.n11ProductSellingService.ProductSellingServicePort)(this)).StartSellingProductBySellerCodeAsync(inValue);
        }
    }
}
