//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lystikaServer.n11ShipmentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.n11.com/ws/schemas", ConfigurationName="n11ShipmentService.ShipmentServicePort")]
    public interface ShipmentServicePort {
        
        // CODEGEN: CreateOrUpdateShipmentTemplate işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse1 CreateOrUpdateShipmentTemplate(lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse1> CreateOrUpdateShipmentTemplateAsync(lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest1 request);
        
        // CODEGEN: GetShipmentTemplate işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        lystikaServer.n11ShipmentService.GetShipmentTemplateResponse1 GetShipmentTemplate(lystikaServer.n11ShipmentService.GetShipmentTemplateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.GetShipmentTemplateResponse1> GetShipmentTemplateAsync(lystikaServer.n11ShipmentService.GetShipmentTemplateRequest1 request);
        
        // CODEGEN: GetShipmentTemplateList işlemi RPC ya da belge kaydırmalı olmadığından, ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse1 GetShipmentTemplateList(lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse1> GetShipmentTemplateListAsync(lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class CreateOrUpdateShipmentTemplateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private ShipmentApiModel shipmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ShipmentApiModel shipment {
            get {
                return this.shipmentField;
            }
            set {
                this.shipmentField = value;
                this.RaisePropertyChanged("shipment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appKeyField;
        
        private string appSecretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("appKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appSecret {
            get {
                return this.appSecretField;
            }
            set {
                this.appSecretField = value;
                this.RaisePropertyChanged("appSecret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
                this.RaisePropertyChanged("errorCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ShipmentCompanyApiModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string shortNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("shortName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class CityApiModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class DistrictApiModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ShipmentSaveAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string addressField;
        
        private DistrictApiModel districtField;
        
        private CityApiModel cityField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DistrictApiModel district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("district");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public CityApiModel city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ShipmentApiModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string templateNameField;
        
        private string installmentInfoField;
        
        private string exchangeInfoField;
        
        private string shippingInfoField;
        
        private bool specialDeliveryField;
        
        private string deliveryFeeTypeField;
        
        private bool combinedShipmentAllowedField;
        
        private string shipmentMethodField;
        
        private ShipmentSaveAddress warehouseAddressField;
        
        private ShipmentSaveAddress exchangeAddressField;
        
        private ShipmentCompanyApiModel[] shipmentCompaniesField;
        
        private CityApiModel[] deliverableCitiesField;
        
        private ShipmentCompanyApiModel claimShipmentCompanyField;
        
        private string cargoAccountNoField;
        
        private bool useDmallCargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string templateName {
            get {
                return this.templateNameField;
            }
            set {
                this.templateNameField = value;
                this.RaisePropertyChanged("templateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string installmentInfo {
            get {
                return this.installmentInfoField;
            }
            set {
                this.installmentInfoField = value;
                this.RaisePropertyChanged("installmentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string exchangeInfo {
            get {
                return this.exchangeInfoField;
            }
            set {
                this.exchangeInfoField = value;
                this.RaisePropertyChanged("exchangeInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string shippingInfo {
            get {
                return this.shippingInfoField;
            }
            set {
                this.shippingInfoField = value;
                this.RaisePropertyChanged("shippingInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool specialDelivery {
            get {
                return this.specialDeliveryField;
            }
            set {
                this.specialDeliveryField = value;
                this.RaisePropertyChanged("specialDelivery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string deliveryFeeType {
            get {
                return this.deliveryFeeTypeField;
            }
            set {
                this.deliveryFeeTypeField = value;
                this.RaisePropertyChanged("deliveryFeeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool combinedShipmentAllowed {
            get {
                return this.combinedShipmentAllowedField;
            }
            set {
                this.combinedShipmentAllowedField = value;
                this.RaisePropertyChanged("combinedShipmentAllowed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string shipmentMethod {
            get {
                return this.shipmentMethodField;
            }
            set {
                this.shipmentMethodField = value;
                this.RaisePropertyChanged("shipmentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ShipmentSaveAddress warehouseAddress {
            get {
                return this.warehouseAddressField;
            }
            set {
                this.warehouseAddressField = value;
                this.RaisePropertyChanged("warehouseAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ShipmentSaveAddress exchangeAddress {
            get {
                return this.exchangeAddressField;
            }
            set {
                this.exchangeAddressField = value;
                this.RaisePropertyChanged("exchangeAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("shipmentCompany", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ShipmentCompanyApiModel[] shipmentCompanies {
            get {
                return this.shipmentCompaniesField;
            }
            set {
                this.shipmentCompaniesField = value;
                this.RaisePropertyChanged("shipmentCompanies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("city", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CityApiModel[] deliverableCities {
            get {
                return this.deliverableCitiesField;
            }
            set {
                this.deliverableCitiesField = value;
                this.RaisePropertyChanged("deliverableCities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public ShipmentCompanyApiModel claimShipmentCompany {
            get {
                return this.claimShipmentCompanyField;
            }
            set {
                this.claimShipmentCompanyField = value;
                this.RaisePropertyChanged("claimShipmentCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string cargoAccountNo {
            get {
                return this.cargoAccountNoField;
            }
            set {
                this.cargoAccountNoField = value;
                this.RaisePropertyChanged("cargoAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool useDmallCargo {
            get {
                return this.useDmallCargoField;
            }
            set {
                this.useDmallCargoField = value;
                this.RaisePropertyChanged("useDmallCargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class CreateOrUpdateShipmentTemplateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ShipmentApiModel shipmentTemplateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ShipmentApiModel shipmentTemplate {
            get {
                return this.shipmentTemplateField;
            }
            set {
                this.shipmentTemplateField = value;
                this.RaisePropertyChanged("shipmentTemplate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrUpdateShipmentTemplateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest CreateOrUpdateShipmentTemplateRequest;
        
        public CreateOrUpdateShipmentTemplateRequest1() {
        }
        
        public CreateOrUpdateShipmentTemplateRequest1(lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest CreateOrUpdateShipmentTemplateRequest) {
            this.CreateOrUpdateShipmentTemplateRequest = CreateOrUpdateShipmentTemplateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrUpdateShipmentTemplateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse CreateOrUpdateShipmentTemplateResponse;
        
        public CreateOrUpdateShipmentTemplateResponse1() {
        }
        
        public CreateOrUpdateShipmentTemplateResponse1(lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse CreateOrUpdateShipmentTemplateResponse) {
            this.CreateOrUpdateShipmentTemplateResponse = CreateOrUpdateShipmentTemplateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetShipmentTemplateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetShipmentTemplateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ShipmentApiModel shipmentTemplateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ShipmentApiModel shipmentTemplate {
            get {
                return this.shipmentTemplateField;
            }
            set {
                this.shipmentTemplateField = value;
                this.RaisePropertyChanged("shipmentTemplate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipmentTemplateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ShipmentService.GetShipmentTemplateRequest GetShipmentTemplateRequest;
        
        public GetShipmentTemplateRequest1() {
        }
        
        public GetShipmentTemplateRequest1(lystikaServer.n11ShipmentService.GetShipmentTemplateRequest GetShipmentTemplateRequest) {
            this.GetShipmentTemplateRequest = GetShipmentTemplateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipmentTemplateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ShipmentService.GetShipmentTemplateResponse GetShipmentTemplateResponse;
        
        public GetShipmentTemplateResponse1() {
        }
        
        public GetShipmentTemplateResponse1(lystikaServer.n11ShipmentService.GetShipmentTemplateResponse GetShipmentTemplateResponse) {
            this.GetShipmentTemplateResponse = GetShipmentTemplateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetShipmentTemplateListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetShipmentTemplateListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ShipmentApiModel[] shipmentTemplatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("shipmentTemplate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ShipmentApiModel[] shipmentTemplates {
            get {
                return this.shipmentTemplatesField;
            }
            set {
                this.shipmentTemplatesField = value;
                this.RaisePropertyChanged("shipmentTemplates");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipmentTemplateListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest GetShipmentTemplateListRequest;
        
        public GetShipmentTemplateListRequest1() {
        }
        
        public GetShipmentTemplateListRequest1(lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest GetShipmentTemplateListRequest) {
            this.GetShipmentTemplateListRequest = GetShipmentTemplateListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipmentTemplateListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse GetShipmentTemplateListResponse;
        
        public GetShipmentTemplateListResponse1() {
        }
        
        public GetShipmentTemplateListResponse1(lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse GetShipmentTemplateListResponse) {
            this.GetShipmentTemplateListResponse = GetShipmentTemplateListResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShipmentServicePortChannel : lystikaServer.n11ShipmentService.ShipmentServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShipmentServicePortClient : System.ServiceModel.ClientBase<lystikaServer.n11ShipmentService.ShipmentServicePort>, lystikaServer.n11ShipmentService.ShipmentServicePort {
        
        public ShipmentServicePortClient() {
        }
        
        public ShipmentServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShipmentServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShipmentServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShipmentServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse1 lystikaServer.n11ShipmentService.ShipmentServicePort.CreateOrUpdateShipmentTemplate(lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest1 request) {
            return base.Channel.CreateOrUpdateShipmentTemplate(request);
        }
        
        public lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse CreateOrUpdateShipmentTemplate(lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest CreateOrUpdateShipmentTemplateRequest) {
            lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest1 inValue = new lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest1();
            inValue.CreateOrUpdateShipmentTemplateRequest = CreateOrUpdateShipmentTemplateRequest;
            lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse1 retVal = ((lystikaServer.n11ShipmentService.ShipmentServicePort)(this)).CreateOrUpdateShipmentTemplate(inValue);
            return retVal.CreateOrUpdateShipmentTemplateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse1> lystikaServer.n11ShipmentService.ShipmentServicePort.CreateOrUpdateShipmentTemplateAsync(lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest1 request) {
            return base.Channel.CreateOrUpdateShipmentTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateResponse1> CreateOrUpdateShipmentTemplateAsync(lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest CreateOrUpdateShipmentTemplateRequest) {
            lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest1 inValue = new lystikaServer.n11ShipmentService.CreateOrUpdateShipmentTemplateRequest1();
            inValue.CreateOrUpdateShipmentTemplateRequest = CreateOrUpdateShipmentTemplateRequest;
            return ((lystikaServer.n11ShipmentService.ShipmentServicePort)(this)).CreateOrUpdateShipmentTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lystikaServer.n11ShipmentService.GetShipmentTemplateResponse1 lystikaServer.n11ShipmentService.ShipmentServicePort.GetShipmentTemplate(lystikaServer.n11ShipmentService.GetShipmentTemplateRequest1 request) {
            return base.Channel.GetShipmentTemplate(request);
        }
        
        public lystikaServer.n11ShipmentService.GetShipmentTemplateResponse GetShipmentTemplate(lystikaServer.n11ShipmentService.GetShipmentTemplateRequest GetShipmentTemplateRequest) {
            lystikaServer.n11ShipmentService.GetShipmentTemplateRequest1 inValue = new lystikaServer.n11ShipmentService.GetShipmentTemplateRequest1();
            inValue.GetShipmentTemplateRequest = GetShipmentTemplateRequest;
            lystikaServer.n11ShipmentService.GetShipmentTemplateResponse1 retVal = ((lystikaServer.n11ShipmentService.ShipmentServicePort)(this)).GetShipmentTemplate(inValue);
            return retVal.GetShipmentTemplateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.GetShipmentTemplateResponse1> lystikaServer.n11ShipmentService.ShipmentServicePort.GetShipmentTemplateAsync(lystikaServer.n11ShipmentService.GetShipmentTemplateRequest1 request) {
            return base.Channel.GetShipmentTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.GetShipmentTemplateResponse1> GetShipmentTemplateAsync(lystikaServer.n11ShipmentService.GetShipmentTemplateRequest GetShipmentTemplateRequest) {
            lystikaServer.n11ShipmentService.GetShipmentTemplateRequest1 inValue = new lystikaServer.n11ShipmentService.GetShipmentTemplateRequest1();
            inValue.GetShipmentTemplateRequest = GetShipmentTemplateRequest;
            return ((lystikaServer.n11ShipmentService.ShipmentServicePort)(this)).GetShipmentTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse1 lystikaServer.n11ShipmentService.ShipmentServicePort.GetShipmentTemplateList(lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest1 request) {
            return base.Channel.GetShipmentTemplateList(request);
        }
        
        public lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse GetShipmentTemplateList(lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest GetShipmentTemplateListRequest) {
            lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest1 inValue = new lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest1();
            inValue.GetShipmentTemplateListRequest = GetShipmentTemplateListRequest;
            lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse1 retVal = ((lystikaServer.n11ShipmentService.ShipmentServicePort)(this)).GetShipmentTemplateList(inValue);
            return retVal.GetShipmentTemplateListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse1> lystikaServer.n11ShipmentService.ShipmentServicePort.GetShipmentTemplateListAsync(lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest1 request) {
            return base.Channel.GetShipmentTemplateListAsync(request);
        }
        
        public System.Threading.Tasks.Task<lystikaServer.n11ShipmentService.GetShipmentTemplateListResponse1> GetShipmentTemplateListAsync(lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest GetShipmentTemplateListRequest) {
            lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest1 inValue = new lystikaServer.n11ShipmentService.GetShipmentTemplateListRequest1();
            inValue.GetShipmentTemplateListRequest = GetShipmentTemplateListRequest;
            return ((lystikaServer.n11ShipmentService.ShipmentServicePort)(this)).GetShipmentTemplateListAsync(inValue);
        }
    }
}
